fix release ci linux test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -81,27 +81,39 @@ jobs:
           name: "${{ env.package_name }}"
           path: "${{ github.workspace }}/dist/${{ env.package_name }}"
 
-  # test-macos:
-  #   runs-on:
-  #     - macos-latest
-  #   needs: build-macos
+  test-macos:
+    runs-on:
+      - macos-latest
+    needs: build-macos
 
-  #   steps:
-  #     - name: Get Package Name
-  #       run: |
-  #         package_name=$(/bin/bash build.sh --package-name)
-  #         echo "Package Name: $package_name"
-  #         echo "package_name=$package_name" >> $GITHUB_ENV
-        
-  #     - name: Download Artifact
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: "${{ env.package_name }}"
-  #         path: "${{ github.workspace }}"
-      
-  #     - name: Unpack Artifact
-  #       run: |
-  #         tar -xzf "${{ github.workspace }}/${{ env.package_name }}/${{ env.package_name }}" -C cloudlift --strip-components=1
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Get Package Name
+        run: |
+          package_name=$(/bin/bash build.sh --package-name)
+          echo "Package Name: $package_name"
+          echo "package_name=$package_name" >> $GITHUB_ENV
+
+      - name: Download Artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: "${{ env.package_name }}"
+          path: "${{ github.workspace }}"
+
+      - name: Unpack Artifact
+        run: |
+          tar -xzf "${{ github.workspace }}/${{ env.package_name }}/${{ env.package_name }}" -C cloudlift --strip-components=1
+
+      - name: Run Tests
+        run: |
+          ./cloudlift/cloudlift --version
+
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to run cloudlift on macOS"
+            exit 1
+          fi
 
   test-linux:
     runs-on: ubuntu-latest
@@ -129,6 +141,9 @@ jobs:
             "redhat/ubi8"
           )
           echo "images=${images[@]}" >> $GITHUB_ENV
+
+      - name: Checkout
+        uses: actions/checkout@v4
 
       - name: Get Linux Package Name
         run: |
@@ -166,8 +181,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       - test-linux
-      # - build-macos
-      # - build-linux
+      - test-macos
 
     steps:
       - name: Get and Set Tag
